# 学習データ

In [20]:
import numpy as np

practice1 = "大変ありがたいです"
practice2 = "まじでありがとうございます！"
practice3 = "がちありがとう！"

text1 = '''すごい、、めちゃめちゃ助かります！
ありがとうございます🙇‍♂️
こちらを参考にしながらやってみます！'''
text2 = '''了解です！全然ゆっくりで大丈夫です(excited)'''
text3 = '''本当にありがたいです🥲🥲
平和取り戻しておきます笑'''

# texts = np.array([text1, text2, text3])
# print(texts.shape)
# print(texts[0,])
practices = [practice1, practice2, practice3]
texts = [text1, text2, text3]

# MeCabのインストール

In [2]:
!pip install mecab-python3
!pip install unidic-lite # 辞書インストール

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 577.8/577.8 KB 9.9 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/47.4 MB 9.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for unidic-lite: filename=unidic_lite-1.0.8-py3-none-any.whl size=47658837 sha256=f9e6036d852c72a20d52ff6fb8309a7b1efc5f8792c824e6c5a82ac9733cc7b9
  Stored in directory: /root/.cache/pip/wheels/8c/dd/8f/e21fc192dcd38ae31e1185ce4e66e12df4e811e3d469866e15
Successfully built unidic-lite


In [3]:
import MeCab

# MeCabのオブジェクト生成
wakati = MeCab.Tagger("-Owakati")
# chasen = MeCab.Tagger("-Ochasen") # なんかエラー出た
tagger = MeCab.Tagger()

wakati1 = wakati.parse(text1)
# chasen1 = chasen.parse(text1)
tagger1 = tagger.parse(text1)
print(type(wakati1))
print(wakati1)
print(type(tagger1))
print(tagger1)


<class 'str'>
すごい 、 、 めちゃめちゃ 助かり ます ！ ありがとう ござい ます 🙇 ‍♂ ️ こちら を 参考 に し ながら やっ て み ます ！ 

<class 'str'>
すごい	スゴイ	スゴイ	凄い	形容詞-一般	形容詞	連体形-一般	2
、			、	補助記号-読点			
、			、	補助記号-読点			
めちゃめちゃ	メチャメチャ	メチャメチャ	目茶目茶	副詞			0
助かり	タスカリ	タスカル	助かる	動詞-一般	五段-ラ行	連用形-一般	3
ます	マス	マス	ます	助動詞	助動詞-マス	終止形-一般	
！			！	補助記号-句点			
ありがとう	アリガトー	アリガトウ	有り難う	感動詞-一般			2
ござい	ゴザイ	ゴザル	御座る	動詞-非自立可能	五段-ラ行	連用形-イ音便	2
ます	マス	マス	ます	助動詞	助動詞-マス	終止形-一般	
🙇	🙇	🙇	🙇	補助記号-一般			0
‍♂	‍♂	‍♂	‍♂	記号-一般			0
️	️	️	️	補助記号-一般			0
こちら	コチラ	コチラ	此方	代名詞			0
を	オ	ヲ	を	助詞-格助詞			
参考	サンコー	サンコウ	参考	名詞-普通名詞-サ変可能			0
に	ニ	ニ	に	助詞-格助詞			
し	シ	スル	為る	動詞-非自立可能	サ行変格	連用形-一般	0
ながら	ナガラ	ナガラ	ながら	助詞-接続助詞			
やっ	ヤッ	ヤル	遣る	動詞-非自立可能	五段-ラ行	連用形-促音便	0
て	テ	テ	て	助詞-接続助詞			
み	ミ	ミル	見る	動詞-非自立可能	上一段-マ行	連用形-一般	1
ます	マス	マス	ます	助動詞	助動詞-マス	終止形-一般	
！			！	補助記号-句点			
EOS



# Kerasによる文章のベクトル化



In [4]:
from keras.preprocessing.text import Tokenizer

# Tokenizerをインスタンス化
tokenizer = Tokenizer()
# 文章を与える．
tokenizer.fit_on_texts(texts)

print(type(texts), "length", len(texts))
print("与えられた文章の数：", tokenizer.document_count)
print("与えられた文章内の単語ごとの出現回数：", tokenizer.word_counts)
print("単語ごとに割り当てられたインデックス番号", tokenizer.word_index)

# ベクトル化
  # 数字の並び順は word_index 属性で取得できた並びの順．インデックス番号 0 には単語が割り当てられていないので常に0 0 である点に注意
# （バイナリ表現） 
matrix = tokenizer.texts_to_matrix(texts, "binary")
print("\n", "binary:", "\n", matrix)

# （カウント表現） 
matrix = tokenizer.texts_to_matrix(texts, "count")
print("\n", "count:", "\n", matrix)

# （TF-IDF表現）Term Frequency - Inverse Document Frequency
# 文章に含まれる単語の重要度を数値化したもの 
matrix = tokenizer.texts_to_matrix(texts, "tfidf")
print("\n", "TF-IDF:", "\n", matrix)


<class 'list'> length 3
与えられた文章の数： 3
与えられた文章内の単語ごとの出現回数： OrderedDict([('すごい、、めちゃめちゃ助かります！', 1), ('ありがとうございます🙇\u200d♂️', 1), ('こちらを参考にしながらやってみます！', 1), ('了解です！全然ゆっくりで大丈夫です', 1), ('excited', 1), ('本当にありがたいです\U0001f972\U0001f972', 1), ('平和取り戻しておきます笑', 1)])
単語ごとに割り当てられたインデックス番号 {'すごい、、めちゃめちゃ助かります！': 1, 'ありがとうございます🙇\u200d♂️': 2, 'こちらを参考にしながらやってみます！': 3, '了解です！全然ゆっくりで大丈夫です': 4, 'excited': 5, '本当にありがたいです\U0001f972\U0001f972': 6, '平和取り戻しておきます笑': 7}

 binary: 
 [[0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]]

 count: 
 [[0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]]

 TF-IDF: 
 [[0.         0.91629073 0.91629073 0.91629073 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.91629073 0.91629073
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.91629073 0.91629073]]


## 分かち書きしてtokenizerを使ってみる

In [5]:
# for文の使い方確認
for i in texts:
  print(i, "\n")

# N = len(texts)
# for i in range(N):
#   print(texts[i], "\n")

すごい、、めちゃめちゃ助かります！
ありがとうございます🙇‍♂️
こちらを参考にしながらやってみます！ 

了解です！全然ゆっくりで大丈夫です(excited) 

本当にありがたいです🥲🥲
平和取り戻しておきます笑 



In [6]:
N = len(texts)
str_texts = []
words_texts = []
for i in range(N):
  # 分かち書き
  str_texts.append(wakati.parse(texts[i]))
  # print(type(str_texts[i]),)
  print(str_texts[i])
  # 単語のlistにしたい
  words_texts.append(str_texts[i].split(' '))
  # print(type(words_texts[i]))
  # print(words_texts[i], "\n")
# print(list_texts)

# binary 
tokenizer = Tokenizer() # Tokenizerの初期化
tokenizer.fit_on_texts(str_texts)
print("与えられた文章の数：", tokenizer.document_count)
print("与えられた文章内の単語ごとの出現回数：", tokenizer.word_counts)
print("単語ごとに割り当てられたインデックス番号", tokenizer.word_index)
binary_texts = tokenizer.texts_to_matrix(str_texts, "binary")
print(binary_texts)

すごい 、 、 めちゃめちゃ 助かり ます ！ ありがとう ござい ます 🙇 ‍♂ ️ こちら を 参考 に し ながら やっ て み ます ！ 

了解 です ！ 全然 ゆっくり で 大丈夫 です ( excited ) 

本当 に ありがたい です 🥲🥲 平和 取り戻し て おき ます 笑 

与えられた文章の数： 3
与えられた文章内の単語ごとの出現回数： OrderedDict([('すごい', 1), ('、', 2), ('めちゃめちゃ', 1), ('助かり', 1), ('ます', 4), ('！', 3), ('ありがとう', 1), ('ござい', 1), ('🙇', 1), ('\u200d♂', 1), ('️', 1), ('こちら', 1), ('を', 1), ('参考', 1), ('に', 2), ('し', 1), ('ながら', 1), ('やっ', 1), ('て', 2), ('み', 1), ('了解', 1), ('です', 3), ('全然', 1), ('ゆっくり', 1), ('で', 1), ('大丈夫', 1), ('excited', 1), ('本当', 1), ('ありがたい', 1), ('\U0001f972\U0001f972', 1), ('平和', 1), ('取り戻し', 1), ('おき', 1), ('笑', 1)])
単語ごとに割り当てられたインデックス番号 {'ます': 1, '！': 2, 'です': 3, '、': 4, 'に': 5, 'て': 6, 'すごい': 7, 'めちゃめちゃ': 8, '助かり': 9, 'ありがとう': 10, 'ござい': 11, '🙇': 12, '\u200d♂': 13, '️': 14, 'こちら': 15, 'を': 16, '参考': 17, 'し': 18, 'ながら': 19, 'やっ': 20, 'み': 21, '了解': 22, '全然': 23, 'ゆっくり': 24, 'で': 25, '大丈夫': 26, 'excited': 27, '本当': 28, 'ありがたい': 29, '\U0001f972\U0001f972': 30, '平和': 31, '取り戻し': 32, 'おき': 33, '笑': 34}
[

### ver. prctices

In [21]:
N = len(practices)
str_practices = []
words_practices = []
print(practices)
for i in range(N):
  # 分かち書き
  str_practices.append(wakati.parse(practices[i]))
  # 単語のlistにする
  words_practices.append(str_practices[i].split(" "))
print(str_practices)

# 文章をbinaryベクトル化
tokenizer = Tokenizer() # Tokenizerの初期化
tokenizer.fit_on_texts(str_practices) # 文章の適用
print("与えられた文章の数：", tokenizer.document_count)
print("与えられた文章内の単語ごとの出現回数：", tokenizer.word_counts)
print("単語ごとに割り当てられたインデックス番号", tokenizer.word_index)
binary_practices = tokenizer.texts_to_matrix(str_practices, "binary")
print(binary_practices)

['大変ありがたいです', 'まじでありがとうございます！', 'がちありがとう！']
['大変 ありがたい です \n', 'まじ で ありがとう ござい ます ！ \n', 'がち ありがとう ！ \n']
与えられた文章の数： 3
与えられた文章内の単語ごとの出現回数： OrderedDict([('大変', 1), ('ありがたい', 1), ('です', 1), ('まじ', 1), ('で', 1), ('ありがとう', 2), ('ござい', 1), ('ます', 1), ('！', 2), ('がち', 1)])
単語ごとに割り当てられたインデックス番号 {'ありがとう': 1, '！': 2, '大変': 3, 'ありがたい': 4, 'です': 5, 'まじ': 6, 'で': 7, 'ござい': 8, 'ます': 9, 'がち': 10}
[[0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]


# ベルヌーイナイーブベイズ分類器を自作してみる
  - MAP推定
  - 事前分布はディリクレ分布（$alpha=2)
  - クラス数は3つ（C = 3）

In [66]:
professor = ["大変ありがたいです", "本当にありがとうございます"]
senpai = ["まじでありがとうございます！", "ほんとにありがとうございます！"]
friend = ["がちありがとう！", "まじありがとう！"]
all = [professor, senpai, friend]

## とりあえずprofessorに対してやってみる

In [52]:
import numpy as np
import pandas as pd

#やっぱ別にデータフレームにしなくてよさそう
# columns = ["professor"]
# professor_df = pd.DataFrame(data=professor, columns=columns)
# professor_df
# str_professor = professor_df["professor"]
wakati_professor = []
for i in range(len(professor)):
  # 分かち書き
  wakati_professor.append(wakati.parse(professor[i]))
print(wakati_professor)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(wakati_professor)
print("与えられた文章の数：", tokenizer.document_count)
docN_professor = tokenizer.document_count
# print("与えられた文章内の単語ごとの出現回数：", tokenizer.word_counts)
# wordN_professor = tokenizer.word_counts
print("単語ごとに割り当てられたインデックス：", tokenizer.word_index)
wordIx_professor = tokenizer.word_index
binary_professor = tokenizer.texts_to_matrix(wakati_professor, "binary")
print(binary_professor)
len(binary_professor[0])
wordN_professor = np.zeros((1,len(binary_professor[0])))
for i in range(len(binary_professor)):
  wordN_professor = wordN_professor + binary_professor[i,:]
print("単語の統計値：", wordN_professor) # それぞれの単語の統計値
# それぞれの単語の確率
alpha = 2 # 事前分布（ディリクレ分布）
C = 3 # クラス数
p_word_professor = np.zeros((1, len(binary_professor[0])))
p_professor = docN_professor / (docN_professor*C + C * (alpha - 1))
for i in range(len(binary_professor[0])):
  p_word_professor[0,i] = (wordN_professor[0,i] + alpha - 1) / (docN_professor + 2*(alpha-1))

print("それぞれの単語の確率：", p_word_professor)

['大変 ありがたい です \n', '本当 に ありがとう ござい ます \n']
与えられた文章の数： 2
単語ごとに割り当てられたインデックス： {'大変': 1, 'ありがたい': 2, 'です': 3, '本当': 4, 'に': 5, 'ありがとう': 6, 'ござい': 7, 'ます': 8}
[[0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1.]]
単語の統計値： [[0. 1. 1. 1. 1. 1. 1. 1. 1.]]
それぞれの単語の確率： [[0.25 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5 ]]


# ベルヌーイナイーブベイズ分類器っぽいのができた

In [294]:
class NaiveBayes:
  # ここobject指向っぽい
  def __init__(self):
    self
  # def __init__(self, tokenizer):
  #   self.tokenizer = tokenizer
  

  # categoryクラスの中の文章を分かち書き
  def wakatigaki_all(self, categories):
    wakati = MeCab.Tagger("-Owakati")
    categories_1d = list(itertools.chain.from_iterable(categories))
    wakati_categories = []
    for i in range(len(categories_1d)):
      wakati_categories.append(wakati.parse(categories_1d[i]))
    # print(wakati_categories)
    return wakati_categories

  # 各カテゴリの文章を分かち書き
  def wakatigaki_each(self, category):
    wakati = MeCab.Tagger("-Owakati")
    wakati_category = []
    for i in range(len(category)):
      wakati_category.append(wakati.parse(category[i]))
    # print(wakati_category)
    return wakati_category

  # 分かち書きされた文章をbinary化
  def binary_vector(self, categories):
    wakati_categories = self.wakatigaki_all(categories)
    wakati_category = []
    for i in categories:
      wakati_category.append(self.wakatigaki_each(i))
    # print(wakati_category)
    # print(wakati_categories)
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(wakati_categories)
    # print("すべての文章の数：", tokenizer.document_count)
    N_all = tokenizer.document_count
    # print("単語ごとのインデックス：", tokenizer.word_index)
    # binary_categories = tokenizer.texts_to_matrix(wakati_categories, "binary")
    binary_category = []
    for i in wakati_category:
      binary_category.append(tokenizer.texts_to_matrix(i, "binary"))
    return binary_category

  # 各単語の統計値
  def statistics_word(self, categories):
    binary_category = self.binary_vector(categories)
    N_words = np.zeros((3,len(binary_category[0][0])))
    # print(binary_category[0][0])
    for i in range(len(binary_category)):
      for j in range(len(binary_category[0])):
        # print(type(binary_category[i][j]))
        N_words[i,:] = N_words[i,:] + binary_category[i][j]
    return N_words

  # MAP推定
  def MAP_estimation(self, categories, alpha, C):
    N_words = self.statistics_word(categories)
    # なんかtokenaizerが変わってたのでもう一回する
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(self.wakatigaki_all(categories))
    N_sentences_all = tokenizer.document_count
    N_sentences = np.zeros((len(categories),1))
    for i in range(len(categories)):
      N_sentences[i,0] = len(categories[i])
    # categoryの確率
    p_category = np.zeros((len(categories),1))
    for i in range(len(categories)):
      p_category[i,0] = (N_sentences[i,0] + (alpha-1)) / (N_sentences_all + C * (alpha-1))
    # print(p_category)
    # 各categoryにおける各単語の確率
    p_words = np.zeros((len(categories), len(N_words[0])))
    for i in range(len(categories)):
      for j in range(len(N_words[0])):
        p_words[i,j] = (N_words[i,j] + (alpha-1)) / (N_sentences[i,0] + C * (alpha-1))
    return p_category, p_words

  # テストデータを入れて確認
  def test(self, categories, alpha, C, test_data):
    p_category = self.MAP_estimation(categories, alpha, C)[0]
    p_words = self.MAP_estimation(categories, alpha, C)[1]

    wakati_test = wakati.parse(test_data)
    tokenizer = Tokenizer() # またtokenizer作り
    tokenizer.fit_on_texts(self.wakatigaki_all(categories))
    # testdataをbinary化
    binary_test = tokenizer.texts_to_matrix([wakati_test], "binary")
    # どのcategoryになる確率が一番高いかを計算
    p_test = np.zeros((len(p_category),1))
    for i in range(len(p_category)):
      p_test[i,0] = p_category[i,0]
      for j in range(len(binary_test[0])):
        if binary_test[0][j] == 1.0:
          p_test[i,0] = p_test[i,0] * p_words[i][j]
        elif binary_test[0][j] == 0.0:
          p_test[i,0] = p_test[i,0] * (1 - p_words[i][j])
    print("確率最大のインデックス：", np.argmax(p_test))
    return p_test
    

In [295]:
import itertools
import numpy as np

naivebayes = NaiveBayes()
# naivebayes.wakatigaki_each(professor)
# print(naivebayes.binary_vector(all))
# naivebayes.MAP_estimation(all, 2, 3) # これで分類器が作れた？
test_data = "まじか！さすが！"
naivebayes.test(all, 2, 3, test_data)

確率最大のインデックス： 2


array([[0.00036692],
       [0.00043487],
       [0.00309238]])